"""empty message

Revision ID: 2cf7cfad242e
Revises: 9e7c2af77e52
Create Date: 2021-12-18 10:16:52.723705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cf7cfad242e'
down_revision = '9e7c2af77e52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.FLOAT(), nullable=False))

    # ### end Alembic commands ###
