"""empty message

Revision ID: 5157ebd15c73
Revises: 2cf7cfad242e
Create Date: 2021-12-18 10:52:06.142391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5157ebd15c73'
down_revision = '2cf7cfad242e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('name')
        batch_op.drop_column('detail_address')
        batch_op.drop_column('address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('detail_address', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=255), nullable=False))

    # ### end Alembic commands ###
