"""empty message

Revision ID: 9e7c2af77e52
Revises: a2d963f76692
Create Date: 2021-12-17 23:07:45.241430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e7c2af77e52'
down_revision = 'a2d963f76692'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery', schema=None) as batch_op:
        batch_op.drop_constraint('uq_delivery_user_id', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_delivery_user_id', ['user_id'])

    # ### end Alembic commands ###
