"""empty message

Revision ID: a2d963f76692
Revises: 4acb89c40e00
Create Date: 2021-12-17 23:06:14.943560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2d963f76692'
down_revision = '4acb89c40e00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_delivery_user_id'), ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_delivery_user_id'), type_='unique')

    # ### end Alembic commands ###
