"""empty message

Revision ID: bfdc041e190b
Revises: cdb66e317f25
Create Date: 2021-12-11 16:21:18.896979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfdc041e190b'
down_revision = 'cdb66e317f25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cloth', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cloth', schema=None) as batch_op:
        batch_op.drop_column('url')

    # ### end Alembic commands ###
